### PR TITLE
Remove calls to GetShallowClone

### LINKED ISSUE #246: GSA_Toolkit: Replace calls to Clone methods with calls to Base DeepClone or ShallowClone
#### Broken rules:
See https://github.com/BHoM/admin/issues/9

#### Suggestions to restore compliance:
https://github.com/BHoM/admin/issues/9#issuecomment-709032648

### PR DESCRIPTION
**Pull request by alelom**
### Issues addressed by this PR

 Closes #246 

See BHoM/admin#9
 

 ### Test files

Just compliance, should mean no functional change.

 ### Changelog

 ### Additional comments

### CODE REVIEW

File: GSA_Adapter/Convert/FromGsa/Properties/SectionProperty.cs [hunk 1]
```diff
@@ -126,7 +127,7 @@ public static ISectionProperty FromGsaSectionProperty(string gsaString, Dictiona
 
                     if (secProp != null)
                     {
-                        secProp = secProp.GetShallowClone() as ISectionProperty;
+                        secProp = secProp.ShallowClone() as ISectionProperty;
```
Comment (FraserGreenroyd) [inline GSA_Adapter/Convert/FromGsa/Properties/SectionProperty.cs:130]:
```suggestion
                        secProp = secProp.ShallowClone();
```

File: GSA_Adapter/Convert/ToGsa/Properties/Material.cs [hunk 2]
```diff
@@ -148,7 +149,7 @@ private static MaterialType GetMaterialType(IMaterialFragment material)
         private static IOrthotropic CheckMaterialVectors(this IOrthotropic material)
         {
             List<string> failingProperties = new List<string>();
-            IOrthotropic clone = material.GetShallowClone() as IOrthotropic;
+            IOrthotropic clone = material.ShallowClone() as IOrthotropic;
```
Comment (FraserGreenroyd) [inline GSA_Adapter/Convert/ToGsa/Properties/Material.cs:152]:
```suggestion
            IOrthotropic clone = material.ShallowClone();
```

File: GSA_Engine/Modify/SetAnalysisType.cs [hunk 3]
```diff
@@ -45,7 +46,7 @@ public static partial class Modify
         public static LoadCombination SetAnalysisType(LoadCombination loadcombination, AnalysisType analysisType = AnalysisType.LinearStatic, int stage = 0)
         {
             AnalysisTaskFragment fragment = new AnalysisTaskFragment { AnalysisType = analysisType, Stage = stage };
-            LoadCombination clone = loadcombination.GetShallowClone() as LoadCombination;
+            LoadCombination clone = loadcombination.ShallowClone() as LoadCombination;
```
Comment (FraserGreenroyd) [inline GSA_Engine/Modify/SetAnalysisType.cs:49]:
```suggestion
            LoadCombination clone = loadcombination.ShallowClone();
```

**Review by FraserGreenroyd — CHANGES_REQUESTED** [review]

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required
@BHoMBot check dataset-compliance
@BHoMBot check copyright-compliance
@BHoMBot check ready-to-merge

**Review by FraserGreenroyd — APPROVED** [review]
Code reviewed only.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 3189842901

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge
