### PR TITLE
Fix issue pushing gravity loads with meshes with more than one face

### LINKED ISSUE #258: Gravity loads on Meshes with multiple faces fail to push
#### Description:

Pushing gravity loads assigned to a mesh with multiple faces currently fail. This is not an issue if loads are assigned to elements pulled from GSA, but affects pushing loads using the output from a PushComponent with FEMeshes

#### Steps to reproduce:

Push a FEMesh with more than one face, then add the result to a GravityLoad and push the gravity load.

#### Expected behaviour:

For the GravityLoad to be applied to all faces of the pushed FEMesh

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### NOTE: Depends on 

 ### Issues addressed by this PR

 Closes #258

 

Special case for getting ids from FEMesh

Get Ids from FEFaces instead of host FEMesh when producing IDList.

Adding in OrderBy to ensure IDString is as simple as possible
 ### Test files

https://burohappold.sharepoint.com/:f:/s/BHoM/Esm46kmSSANDghV6Hu9HtH0BxJZNmiT3_IK1NWnd849prw?e=UiKicn

 ### Changelog

 ### Additional comments

### CODE REVIEW

File: GSA_Adapter/Convert/ToGsa/Group.cs [hunk 1]
```diff
@@ -58,12 +58,25 @@ public static partial class Convert
...
+        public static IEnumerable<int> GSAIds(this IBHoMObject obj)
+        {
+            //If FEMesh, then get ID for each face
+            if (obj is FEMesh)
+            {
+                return (obj as FEMesh).Faces.Select(x => x.GSAId());
+            }
+            else
+                return new List<int> { obj.GSAId() };
+        }
```
Comment (alelom) [inline GSA_Adapter/Convert/ToGsa/Group.cs:76]: Shouldn't this new public method reside in the Query class and in its own file instead? Ideally with its own description.

**Review by alelom — CHANGES_REQUESTED** [review]

File: GSA_Adapter/Convert/ToGsa/Group.cs (hunk 1 above)
Comment (alelom) [reply GSA_Adapter/Convert/ToGsa/Group.cs:76]: Sorry didn't realise it was in the Adapter project. Nevermind.

Comment (IsakNaslundBh) [reply GSA_Adapter/Convert/ToGsa/Group.cs:76]: oops, should have been private. Will change

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

File: GSA_Adapter/Convert/ToGsa/Group.cs [hunk 2]
```diff
@@ -58,12 +58,25 @@ public static partial class Convert
                 return "\"" + load.Objects.Name + "\"";
 
             //Otherwise apply to the corresponding indecies
-            return load.Objects.Elements.Select(x => int.Parse(x.GSAId().ToString())).GeterateIdString();
+            return load.Objects.Elements.SelectMany(x => x.GSAIds()).OrderBy(x => x).GeterateIdString();
```
Comment (JosefTaylor) [inline GSA_Adapter/Convert/ToGsa/Group.cs:61]:
```suggestion
            return load.Objects.Elements.SelectMany(x => x.GSAIds()).OrderBy(x => x).GenerateIdString();
```

**Comment by alelom** [comment]
@BHoMBot check required

**Review by JosefTaylor — APPROVED** [review]
Builds OK, but cannot test as I don't have GSA installed.
I suggested a change as a public method name is misspelled, but I don't mind if you don't.

**Comment by alelom** [comment]
@BHoMBot ready-to-merge

File: GSA_Adapter/Convert/ToGsa/Group.cs (hunk 2 above)
Comment (IsakNaslundBh) [reply GSA_Adapter/Convert/ToGsa/Group.cs:61]: As mentioned by @alelom . Prefer to not do any other fixes than more critical bug fixes for the Beta release in this PR. As this has the potential to spill (even if unlikely). I have raised another issue to fix this. https://github.com/BHoM/GSA_Toolkit/issues/260
